const [contractFills, setContract] = useState(
  {
    propertyType: '', 
    land: '', 
    propertyAddress: '', 
    legalDescription: '', 
    personalProperty: '', 
    fixtures: '', 
    otherInforamtion: '', 
    buyerType: '',
    buyerEntity: '',
    buyIndividual: '',
    buyerAddress: '',
    sellerType: '',
    sellerIndividual: '',
    sellerEntity: '',
    sellerAddress: '',
    purchasePrice: '',
    earnestMoneyDeposit: '',
    trustEscrow: '',
    buyerFinancing: '',
    cashOffer: '',
    financingProof: '',
    deedType: '',  // always use warranty deed
    saleOfOtherProperty: '',
    dataRequiredToBeSold: '',
    closingCost: '',
    closingDate: '',
    mineralRights: '',
    surveyProblems: '',
    titleSearchReport: '',
    titleDefects: '',
    inspectionPeriod: '',
    defects: '',
    appraisal: '',
    offerExpiration: '',
    leadDisclosure: '',
    requiredDisclosure: '',
    otherDisclosuresAttachments: '',
    additionalTermsConditions: '',
    realEstateAgent: '',
    effectiveDate: '',
  }
)