const fieldNames = [
  "made on",
  "20",
  "Buyer",
  "Buyer_2",
  "Seller",
  "Seller_2",
  "SingleFamily Home",
  "Condominium",
  "Planned Unit Development PUD",
  "Duplex",
  "Triplex",
  "Fourplex",
  "Other",
  "undefined",
  "Street Address",
  "Tax Parcel Information",
  "Other Description",
  "a payment in the amount of",
  "at","AM","PM Earnest Money",
  "The Earnest Money shall be applied to the Purchase Price at Closing and",
  "is",
  "is not required to be placed in a separate",
  "Buyers Initials",
  "undefined_2",
  "Sellers Initials",
  "undefined_3",
  "payment of",
  "US Dollars",
  "All Cash Offer No loan or financing of any kind is required in order to",
  "AM_2",
  "PM",
  "Seller shall have three 3 business days after the receipt of such",
  "at_2",
  "Bank Financing The Buyers ability to purchase the Property is",
  "Conventional Loan",
  "FHA Loan Attach Required Addendums",
  "VA Loan Attach Required Addendums",
  "Other_2",
  "undefined_4",
  "c On or before",
  "is_2",
  "is not contingent on the lease sale or",
  "Seller with written notice provided to the Buyer within",
  "Buyers Initials_2",
  "undefined_5",
  "Sellers Initials_2",
  "undefined_6",
  "Seller Financing Seller agrees to provide financing to the Buyer",
  "a Loan Amount",
  "b Down Payment",
  "c Interest Rate per annum",
  "d Term",
  "Months",
  "Years",
  "documentation to be provided on or before",
  "The Seller shall have until",
  "Shall not be contingent upon selling another property",
  "Shall be contingent upon selling another property with a mailing",
  "address of",
  "within",
  "Buyer_3",
  "Seller_3",
  "Both Parties The fees and costs",
  "Buyers Initials_3",
  "undefined_7",
  "Sellers Initials_3",
  "undefined_8",
  "CLOSING DATE This transaction shall close on",
  "AM_3",
  "PM or earlier at the office of a title company to",
  "be agreed upon by the Parties Closing Any extension of the Closing must",
  "later than",
  "to the Property Seller shall be required to remedy such defects within",
  "Upon receipt of the Title Search Report the Buyer shall have",
  "defect the Seller shall have",
  "Buyers Initials_4",
  "undefined_9",
  "Sellers Initials_4",
  "undefined_10",
  "qualified professionals to further inspect and investigate the Property until",
  "at_3",
  "After all inspections are completed Buyer shall have until",
  "AM_4",
  "PM_2",
  "at_4",
  "Seller in writing The Buyer and Seller shall have",
  "AM_5",
  "PM to present any new property disclosures to the",
  "Buyers Initials_5",
  "undefined_11",
  "Sellers Initials_5",
  "undefined_12",
  "Shall not be contingent upon the appraisal of the Property being",
  "Shall be contingent upon the appraisal of the Property being equal to",
  "discovers lenderrequired repairs the Parties shall have",
  "Buyer infull within",
  "Buyers Initials_6",
  "undefined_13",
  "Sellers Initials_6",
  "undefined_14",
  "Buyers Initials_7",
  "undefined_15",
  "Sellers Initials_7",
  "undefined_16",
  "Agreement is personally given to the Buyer by 1",
  "Agreement is personally given to the Buyer by 2",
  "AM_6",
  "PM_3",
  "Buyers Initials_8",
  "undefined_17",
  "Sellers Initials_8",
  "undefined_18",
  "Buyers Initials_9",
  "undefined_19",
  "Sellers Initials_9",
  "undefined_20",
  "There are no attached addendums or disclosures to this Agreement",
  "The following addendums or disclosures are attached to this",
  "Building Code or Zoning Ordinance Violations Disclosure",
  "LeadBased Paint Disclosure Form",
  "Methamphetamine Disclosure",
  "Military Air Installation Disclosure",
  "Privately Owned Stormwater Management Facility Disclosure",
  "Repetitive RiskLoss Disclosure",
  "Residential Property Disclosure Statement",
  "Septic System Disclosure",
  "undefined_21",
  "undefined_22",
  "Buyers Initials_10",
  "undefined_23",
  "Sellers Initials_10",
  "undefined_24",
  "Date",
  "Print Name",
  "Date_2",
  "Print Name_2",
  "Date_3",
  "Print Name_3",
  "Date_4",
  "Print Name_4",
  "Date_5",
  "Print Name_5",
  "Print Name_6",
  "Date_6",
  "Text1",
  "Text2"
]

